apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: vue-django-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/mysql-data # 这个路径是在你的Docker Desktop虚拟机里的，不是你本地的
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: vue-django-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi