name: Build and Deploy to Local K8s

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    # 1. 关键改动：指定所有步骤默认使用 Windows PowerShell
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. PowerShell 语法保持不变，它在两个版本中都兼容
      - name: Get current date for image tag
        id: date
        run: echo "date=$(Get-Date -Format "yyyyMMddHHmmss")" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Build Backend Docker Image
        run: |
          docker build -t backend-image:latest -t backend-image:${{ steps.date.outputs.date }} ./backend
        
      - name: Build Frontend Docker Image
        run: |
          docker build -t frontend-image:latest -t frontend-image:${{ steps.date.outputs.date }} ./frontend

      - name: Apply K8s Manifests
        run: |
          kubectl apply -f k8s/
      
      - name: Update Backend Deployment Image
        run: |
          # kubectl patch 命令中的 JSON 字符串在 Windows PowerShell 中需要转义，最安全的方式是将其放入变量中
          $patch = '{"spec":{"template":{"spec":{"initContainers":[{"name": "db-migration", "image":"backend-image:${{ steps.date.outputs.date }}"}]}}}}'
          kubectl set image deployment/backend-deployment backend=backend-image:${{ steps.date.outputs.date }} -n vue-django-app
          kubectl patch deployment backend-deployment -n vue-django-app --patch $patch

      - name: Update Frontend Deployment Image
        run: |
          kubectl set image deployment/frontend-deployment frontend=frontend-image:${{ steps.date.outputs.date }} -n vue-django-app

      - name: Verify Deployment Rollout
        run: |
          echo "Verifying backend rollout..."
          kubectl rollout status deployment/backend-deployment -n vue-django-app
          echo "Verifying frontend rollout..."
          kubectl rollout status deployment/frontend-deployment -n vue-django-app