name: Build and Deploy to Local K8s

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    # 指定所有步骤默认使用PowerShell
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. 使用 PowerShell 语法获取日期并设置输出
      - name: Get current date for image tag
        id: date
        run: echo "date=$(Get-Date -Format "yyyyMMddHHmmss")" >> $env:GITHUB_OUTPUT

      - name: Build Backend Docker Image
        run: |
          docker build -t backend-image:latest -t backend-image:${{ steps.date.outputs.date }} ./backend
        
      - name: Build Frontend Docker Image
        run: |
          docker build -t frontend-image:latest -t frontend-image:${{ steps.date.outputs.date }} ./frontend

      - name: Apply K8s Manifests
        run: |
          kubectl apply -f k8s/
      
      # 2. kubectl命令在PowerShell中同样适用
      - name: Update Backend Deployment Image
        run: |
          kubectl set image deployment/backend-deployment backend=backend-image:${{ steps.date.outputs.date }} -n vue-django-app
          kubectl patch deployment backend-deployment -n vue-django-app --patch '{"spec":{"template":{"spec":{"initContainers":[{"name": "db-migration", "image":"backend-image:${{ steps.date.outputs.date }}"}]}}}}'

      - name: Update Frontend Deployment Image
        run: |
          kubectl set image deployment/frontend-deployment frontend=frontend-image:${{ steps.date.outputs.date }} -n vue-django-app

      - name: Verify Deployment Rollout
        run: |
          echo "Verifying backend rollout..."
          kubectl rollout status deployment/backend-deployment -n vue-django-app
          echo "Verifying frontend rollout..."
          kubectl rollout status deployment/frontend-deployment -n vue-django-app